# Generated by Django 3.0.5 on 2020-04-18 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Temperatura')),
                ('hum', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Humedad')),
                ('temp_cpu', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Temperatura CPU')),
                ('temp_gpu', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Temperatura GPU')),
                ('disk_cap', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Uso del disco')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=8, verbose_name='Sensor')),
            ],
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.AddField(
            model_name='muestra',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.Sensor'),
        ),
    ]
